DROP TABLE IF EXISTS Mental_Hospital;
DROP TABLE IF EXISTS Outpatient;
DROP TABLE IF EXISTS General_Hospital;
DROP TABLE IF EXISTS Day_Treatment;
DROP TABLE IF EXISTS Patient_Ledger;
DROP TABLE IF EXISTS Facility;
DROP TABLE IF EXISTS Suicide_Rates;
DROP TABLE IF EXISTS Country;