LOAD DATA LOCAL INFILE '.suicide_rates/.csv' INTO TABLE Suicide_Rates FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE '.facility/.csv' INTO TABLE Facility FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE '.mh/.csv' INTO TABLE Mental_Hospital FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE '.mhu/.csv' INTO TABLE General_Hospital FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE '.outpatient/.csv' INTO TABLE Outpatient FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE '.day_treatment/.csv' INTO TABLE Day_Treatment FIELDS TERMINATED BY ',';